[package]
name = "realm"
version = "0.1.0"
authors = ["Amit Upadhyay <amitu@acko.com>"]
description = "Rust / Elm base full stack web framework."
license = "BSD-2-Clause"
edition = "2018"

[dependencies]
hyper = "~0.12.27"
futures-cpupool = "~0.1.8"
lazy_static = "~1.2.0"
futures = "~0.1.26"
antidote = "~1.0.0"
thread-id = "~3.3.0"
http = "~0.1.17"

[dev-dependencies]
pretty_assertions = "~0.5.1"
