# Generated by Django 3.0.6 on 2020-05-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("okind", models.TextField()),
                ("oid", models.TextField()),
                ("ekind", models.TextField()),
                ("data", models.TextField()),
                ("trace", models.TextField()),
                ("response", models.TextField()),
                ("who", models.TextField(null=True)),
                ("when", models.DateTimeField(auto_now_add=True)),
                ("ip", models.TextField(max_length=39)),
                ("session", models.TextField(null=True)),
                ("app", models.TextField(blank=True)),
                ("site_version", models.TextField()),
            ],
        )
    ]
