# Generated by Django 3.1 on 2020-09-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realm", "0002_activity_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity", old_name="session", new_name="rust_trace",
        ),
        migrations.RenameField(model_name="activity", old_name="who", new_name="sid",),
        migrations.RemoveField(model_name="activity", name="app",),
        migrations.AddField(
            model_name="activity", name="code", field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="activity",
            name="duration",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="activity", name="hash", field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="activity", name="method", field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="activity", name="outcome", field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="activity", name="tid", field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="activity",
            name="tid_created",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activity", name="ua", field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="activity", name="uid", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="utm_campaign",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="utm_content",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="activity", name="utm_medium", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="activity", name="utm_source", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="activity", name="utm_term", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="activity", name="vid", field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="activity",
            name="vid_created",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="activity", name="data", field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="activity",
            name="response",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="activity", name="trace", field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="activity", name="url", field=models.TextField(default=""),
        ),
    ]
