# Generated by Django 3.1.2 on 2021-02-15 14:06

from django.db import migrations, models
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0004_task'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.AddField(
            model_name='task',
            name='cookies',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='task',
            name='method',
            field=models.TextField(default='POST'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='path',
            field=models.TextField(default='/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
